### PR TITLE
field workflow_state will not automaticly be defined

### PR DESCRIPTION
**Pull request by rynr**
see https://github.com/bowsersenior/workflow_on_mongoid/issues/5

### CODE REVIEW

**Comment by rynr** [comment]
Just commenting, why i think this should be included:
When including Workflow into a Document, the field "workflow_state" will automatic be created though it probably is not required. When later the workflow_column is set to another field, the workflow_field will remain unused.
For the ActiveRecord-Implementation, the behavior is the same.

**Comment by bowsersenior** [comment]
Thanks for your contribution, Rainer. I'll have a look at this soon. By the way, it would be great if you could write a couple of tests for the scenario you described!

**Comment by bowsersenior** [comment]
OK, I added a couple of small tests and merged your commits. Thanks again!

**Comment by bowsersenior** [comment]
Also, I pushed an updated version of the gem (0.8.0.5) that includes your commits.

**Comment by rynr** [comment]
Thanks very much!

**Pull request merged**
